### PR TITLE
updated react to 15.0.0 updated version to 3.0.0

### PR DESCRIPTION
**Pull request by H34D**

### CODE REVIEW

**Comment by qimingweng** [comment]
Hi @H34D I think we can make the dependency looser, something like `^14.0.0 | ^15.0.0`

**Comment by H34D** [comment]
sure, i can do this

**Comment by H34D** [comment]
updated my pull request @qimingweng

**Comment by H34D** [comment]
why you no merge?

**Comment by qimingweng** [comment]
@H34D Thanks for being patient

**Pull request merged**
